#include "ECSS_Configuration.hpp"

#ifdef SERVICE_PARAMETER

#include "Services/ParameterService.hpp"
#include "AcubeSATParameters.hpp"

void ParameterService::initializeParameterMap() {
    parameters = {{AcubeSATParameters::OBCMCUTemperature, AcubeSATParameters::obcMCUTemperature},
                  {AcubeSATParameters::OBCUseRTT, AcubeSATParameters::obcUseRTT},
                  {AcubeSATParameters::OBCUseUART, AcubeSATParameters::obcUseUART},
                  {AcubeSATParameters::OBCUseCAN, AcubeSATParameters::obcUseCAN},
                  //-----------------------------------------------------------------------------------------------
                  {AcubeSATParameters::OBCPCBTemperature1, AcubeSATParameters::obcPCBTemperature1},
                  {AcubeSATParameters::OBCPCBTemperature2, AcubeSATParameters::obcPCBTemperature2},
                  {AcubeSATParameters::OBCMCUInputVoltage, AcubeSATParameters::obcMCUInputVoltage},
                  {AcubeSATParameters::OBCMCUBootCounter, AcubeSATParameters::obcMCUBootCounter},
                  {AcubeSATParameters::OBCFlashInt, AcubeSATParameters::obcFlashInt},
                  {AcubeSATParameters::OBCSRAMInt, AcubeSATParameters::obcSRAMInt},
                  {AcubeSATParameters::OBCAvailableMRAM, AcubeSATParameters::obcAvailableMRAM},
                  {AcubeSATParameters::OBCAvailableNAND, AcubeSATParameters::obcAvailableNAND},
                  {AcubeSATParameters::OBCSpacecraftTimeRef, AcubeSATParameters::obcSpacecraftTimeRef},
                  {AcubeSATParameters::OBCOnBoardTime, AcubeSATParameters::obcOnBoardTime},
                  {AcubeSATParameters::OBCOperationalMode, AcubeSATParameters::obcOperationalMode},
                  {AcubeSATParameters::OBCMemoryPartition, AcubeSATParameters::obcMemoryPartition},
                  {AcubeSATParameters::OBCReconfigurationTimer, AcubeSATParameters::obcReconfigurationTimer},
                  {AcubeSATParameters::OBCLastFailedEvent, AcubeSATParameters::obcLastFailedEvent},
                  {AcubeSATParameters::OBCMCUSystick, AcubeSATParameters::obcMCUSystick},
                  {AcubeSATParameters::OBCCANBUSLoad1, AcubeSATParameters::obcCANBUSLoad1},
                  {AcubeSATParameters::OBCCANBUSLoad2, AcubeSATParameters::obcCANBUSLoad2},
                  {AcubeSATParameters::OBCCANBUSActive, AcubeSATParameters::obcCANBUSActive},
                  {AcubeSATParameters::OBCMCUFDIR, AcubeSATParameters::obcMCUFDIR},
                  {AcubeSATParameters::OBCMCURestartSafeModeThreshold, AcubeSATParameters::obcMCURestartSafeModeThreshold},
                  {AcubeSATParameters::OBCNANDFLASHLCLThreshold, AcubeSATParameters::obcNANDFLASHLCLThreshold},
                  {AcubeSATParameters::OBCMRAMLCLThreshold, AcubeSATParameters::obcMRAMLCLThreshold},
                  {AcubeSATParameters::OBCNANDFLASHON, AcubeSATParameters::obcNANDFLASHON},
                  {AcubeSATParameters::OBCMRAMON, AcubeSATParameters::obcNANDFlashScrubbingFrequency},
                  {AcubeSATParameters::OBCNANDFLASHScrubbingFrequency, AcubeSATParameters::obcMRAMON},
                  {AcubeSATParameters::OBCRAMScrubbingFrequency, AcubeSATParameters::obcRAMScrubbingFrequency},
                  {AcubeSATParameters::OBCProgramFlashScrubbingFrequency, AcubeSATParameters::obcProgramFlashScrubbingFrequency},
                  //-----------------------------------------------------------------------------------------------
                  {AcubeSATParameters::SUMCUBootCounter, AcubeSATParameters::suMCUBootCounter},
                  {AcubeSATParameters::SUMCUSysTick, AcubeSATParameters::suMCUSysTick},
                  {AcubeSATParameters::SUMCUTemperature, AcubeSATParameters::suMCUTemperature},
                  {AcubeSATParameters::SUMCUInputVoltage, AcubeSATParameters::suMCUInputVoltage},
                  {AcubeSATParameters::SUFlashIntUsedPercentage, AcubeSATParameters::suFlashIntUsedPercentage},
                  {AcubeSATParameters::SUFlashUsedPercentage, AcubeSATParameters::suFlashUsedPercentage},
                  {AcubeSATParameters::SUSRAMUsedPercentage, AcubeSATParameters::suSRAMUsedPercentage},
                  {AcubeSATParameters::SUNANDCurrentlyUsedPartition, AcubeSATParameters::suNANDCurrentlyUsedPartition},
                  {AcubeSATParameters::SUNANDFlashLCLOn, AcubeSATParameters::suNANDFlashLclOn},
                  {AcubeSATParameters::SUNANDFlashLCLThreshold, AcubeSATParameters::suNANDFlashLclThreshold},
                  {AcubeSATParameters::SUNANDFlashScrubbingFrequency, AcubeSATParameters::suNANDFlashScrubbingFrequency},
                  {AcubeSATParameters::SURAMScrubbingFrequency, AcubeSATParameters::suRAMScrubbingFrequency},
                  {AcubeSATParameters::SUProgramFlashScrubbingFrequency, AcubeSATParameters::suProgramFlashScrubbingFrequency},
                  {AcubeSATParameters::SUControlPumpFlashLCLOn, AcubeSATParameters::suControlPumpFlashLclOn},
                  {AcubeSATParameters::SUControlPumpFlashLCLThreshold, AcubeSATParameters::suControlPumpFlashLclThreshold},
                  {AcubeSATParameters::SUFlowPumpFlashOn, AcubeSATParameters::suFlowPumpFlashOn},
                  {AcubeSATParameters::SUFlowPumpFlashLCLThreshold, AcubeSATParameters::suFlowPumpFlashLclThreshold},
                  {AcubeSATParameters::SUCameraON, AcubeSATParameters::suCameraOn},
                  {AcubeSATParameters::SUCameraLCLThreshold, AcubeSATParameters::suCameraLCLThreshold},
                  {AcubeSATParameters::SUPCBTemperature1, AcubeSATParameters::suPCBTemperature1},
                  {AcubeSATParameters::SUPCBTemperature2, AcubeSATParameters::suPCBTemperature2},
                  {AcubeSATParameters::SUPCBTemperatureControlValves, AcubeSATParameters::suPCBTemperatureControlValves},
                  {AcubeSATParameters::SUPCBTemperatureFlowValves, AcubeSATParameters::suPCBTemperatureFlowValves},
                  {AcubeSATParameters::SUCameraTemperature, AcubeSATParameters::suCameraTemperature},
                  {AcubeSATParameters::SUPDMSTemperature, AcubeSATParameters::suPDMSTemperature},
                  {AcubeSATParameters::SUGrowthMediumTemperature, AcubeSATParameters::suGrowthMediumTemperature},
                  {AcubeSATParameters::SULastFailedEvent, AcubeSATParameters::suLastFailedEvent},
                  {AcubeSATParameters::SUPressureLevelSensor1, AcubeSATParameters::suPressureLevelSensor1},
                  {AcubeSATParameters::SUPressureLevelSensor2, AcubeSATParameters::suPressureLevelSensor2},
                  {AcubeSATParameters::SUHumidityLevelSensor1, AcubeSATParameters::suHumidityLevelSensor1},
                  {AcubeSATParameters::SUHumidityLevelSensor2, AcubeSATParameters::suHumidityLevelSensor2},
                  {AcubeSATParameters::SURADFET, AcubeSATParameters::suRadfet},
                  {AcubeSATParameters::SUPumpFlowRate1, AcubeSATParameters::suPumpFlowRate1},
                  {AcubeSATParameters::SUPumpFlowRate2, AcubeSATParameters::suPumpFlowRate2},
                  {AcubeSATParameters::SUControlChamberValve1, AcubeSATParameters::suCcontrolChamberValve1},
                  {AcubeSATParameters::SUControlChamberValve2, AcubeSATParameters::suControlChamberValve2},
                  {AcubeSATParameters::SUControlChamberValve3, AcubeSATParameters::suControlChamberValve3},
                  {AcubeSATParameters::SUControlSandwitchValve1, AcubeSATParameters::suControlSandwitchValve1},
                  {AcubeSATParameters::SUControlSandwitchValve2, AcubeSATParameters::suControlSandwitchValve2},
                  {AcubeSATParameters::SUControlSandwitchValve3, AcubeSATParameters::suControlSandwitchValve3},
                  {AcubeSATParameters::SUFlowValveInlet1, AcubeSATParameters::suFlowValveInlet1},
                  {AcubeSATParameters::SUFlowValveInlet2, AcubeSATParameters::suFlowValveInlet2},
                  {AcubeSATParameters::SUFlowValveInlet3, AcubeSATParameters::suFlowValveInlet3},
                  {AcubeSATParameters::SUFlowValveOutlet1, AcubeSATParameters::suFlowValveOutlet1},
                  {AcubeSATParameters::SUFlowValveOutlet2, AcubeSATParameters::suFlowValveOutlet2},
                  {AcubeSATParameters::SUFlowValveOutlet3, AcubeSATParameters::suFlowValveOutlet3},
                  {AcubeSATParameters::SUFlowValveTest1, AcubeSATParameters::suFlowValveTest1},
                  {AcubeSATParameters::SUFlowValveTest2, AcubeSATParameters::suFlowValveTest2},
                  {AcubeSATParameters::SULEDIntensity1, AcubeSATParameters::suLEDIntensity1},
                  {AcubeSATParameters::SULEDIntensity2, AcubeSATParameters::suLEDIntensity2},
                  {AcubeSATParameters::SULEDIntensity3, AcubeSATParameters::suLEDIntensity3},
                  {AcubeSATParameters::SULEDIntensity4, AcubeSATParameters::suLEDIntensity4},
                  {AcubeSATParameters::SUNumberOfPhotosTaken, AcubeSATParameters::suNumberOfPhotosTaken},
                  {AcubeSATParameters::SUPhotoExposureTime, AcubeSATParameters::suPhotoExposureTime},
                  {AcubeSATParameters::SUPhotoInterval, AcubeSATParameters::suPhotoInterval},
                  {AcubeSATParameters::SUPhotoCroppedResolution, AcubeSATParameters::suPhotoCroppedResolution},
                  {AcubeSATParameters::SUPhotoCompressionRate, AcubeSATParameters::suPhotoCompressionRate},
                  {AcubeSATParameters::SUExperimentNumber, AcubeSATParameters::suExperimentNumber},
                  {AcubeSATParameters::SUOnBoardTime, AcubeSATParameters::suOnBoardTime},
                  {AcubeSATParameters::SUTemperatureFromHumiditySensor1, AcubeSATParameters::suTemperatureFromHumiditySensor1},
                  {AcubeSATParameters::SUTemperatureFromHumiditySensor2, AcubeSATParameters::suTemperatureFromHumiditySensor2},
                  //---------------------------------------------------------------------------------------------
                  {AcubeSATParameters::ADCSUseRTT, AcubeSATParameters::adcsUseRTT},
                  {AcubeSATParameters::ADCSUseUART, AcubeSATParameters::adcsUseUART},
                  {AcubeSATParameters::ADCSUseCAN, AcubeSATParameters::adcsUseCAN},
                  {AcubeSATParameters::ADCSXBodyFrameRegardingOrbitFrame, AcubeSATParameters::adcsXBodyFrameRegardingOrbitFrame},
                  {AcubeSATParameters::ADCSYBodyFrameRegardingOrbitFrame, AcubeSATParameters::adcsYBodyFrameRegardingOrbitFrame},
                  {AcubeSATParameters::ADCSZBodyFrameRegardingOrbitFrame, AcubeSATParameters::adcsZBodyFrameRegardingOrbitFrame},
                  {AcubeSATParameters::ADCSAngularVelocityOnX, AcubeSATParameters::adcsAngularVelocityOnX},
                  {AcubeSATParameters::ADCSAngularVelocityOnY, AcubeSATParameters::adcsAngularVelocityOnY},
                  {AcubeSATParameters::ADCSAngularVelocityOnZ, AcubeSATParameters::adcsAngularVelocityOnZ},
                  {AcubeSATParameters::ADCSBDotXAxis, AcubeSATParameters::adcsBDotXAxis},
                  {AcubeSATParameters::ADCSBDotYAxis, AcubeSATParameters::adcsBDotYAxis},
                  {AcubeSATParameters::ADCSBDotZAxis, AcubeSATParameters::adcsBDotZAxis},
                  {AcubeSATParameters::ADCSQuaternionOrbitFrameToBodyScalar, AcubeSATParameters::adcsQuaternionOrbitFrameToBodyScalar},
                  {AcubeSATParameters::ADCSQuaternionOrbitFrameToBodyVectorElem1, AcubeSATParameters::adcsQuaternionOrbitFrameToBodyVectorElem1},
                  {AcubeSATParameters::ADCSQuaternionOrbitFrameToBodyVectorElem2, AcubeSATParameters::adcsQuaternionOrbitFrameToBodyVectorElem2},
                  {AcubeSATParameters::ADCSQuaternionOrbitFrameToBodyVectorElem3, AcubeSATParameters::adcsQuaternionOrbitFrameToBodyVectorElem3},
                  {AcubeSATParameters::ADCSMCUTemperature, AcubeSATParameters::adcsMCUTemperature},
                  {AcubeSATParameters::ADCSBootCounter, AcubeSATParameters::adcsBootCounter},
                  {AcubeSATParameters::ADCSOnBoardTime, AcubeSATParameters::adcsOnBoardTime},
                  {AcubeSATParameters::ADCSSystick, AcubeSATParameters::adcsSystick},
                  {AcubeSATParameters::ADCSMagnetometerRawX, AcubeSATParameters::adcsMagnetometerRawX},
                  {AcubeSATParameters::ADCSMagnetometerRawY, AcubeSATParameters::adcsMagnetometerRawY},
                  {AcubeSATParameters::ADCSMagnetometerRawZ, AcubeSATParameters::adcsMagnetometerRawZ},
                  {AcubeSATParameters::ADCSMagnetometerFrequency, AcubeSATParameters::adcsMagnetometerFrequency},
                  {AcubeSATParameters::ADCSMagnetometerCycleCountX, AcubeSATParameters::adcsMagnetometerCycleCountX},
                  {AcubeSATParameters::ADCSMagnetometerCycleCountY, AcubeSATParameters::adcsMagnetometerCycleCountY},
                  {AcubeSATParameters::ADCSMagnetometerCycleCountZ, AcubeSATParameters::adcsMagnetometerCycleCountZ},
                  {AcubeSATParameters::ADCSMagnetometerSelfTest, AcubeSATParameters::adcsMagnetometerSelfTest},
                  {AcubeSATParameters::ADCSMagnetometerISISCalibratedXAxis, AcubeSATParameters::adcsMagnetometerISISCalibratedXAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISCalibratedYAxis, AcubeSATParameters::adcsMagnetometerISISCalibratedYAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISCalibratedZAxis, AcubeSATParameters::adcsMagnetometerISISCalibratedZAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISFilteredXAxis, AcubeSATParameters::adcsMagnetometerISISFilteredXAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISFilteredYAxis, AcubeSATParameters::adcsMagnetometerISISFilteredYAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISFilteredZAxis, AcubeSATParameters::adcsMagnetometerISISFilteredZAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISRawXAxis, AcubeSATParameters::adcsMagnetometerISISRawXAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISRawYAxis, AcubeSATParameters::adcsMagnetometerISISRawYAxis},
                  {AcubeSATParameters::ADCSMagnetometerISISRawZAxis, AcubeSATParameters::adcsMagnetometerISISRawZAxis},
                  {AcubeSATParameters::ADCSFineSunSensorRawTopLeft, AcubeSATParameters::adcsFineSunSensorRawTopLeft},
                  {AcubeSATParameters::ADCSFineSunSensorRawTopRight, AcubeSATParameters::adcsFineSunSensorRawTopRight},
                  {AcubeSATParameters::ADCSFineSunSensorRawBottomLeft, AcubeSATParameters::adcsFineSunSensorRawBottomLeft},
                  {AcubeSATParameters::ADCSFineSunSensorRawBottomRight, AcubeSATParameters::adcsFineSunSensorRawBottomRight},
                  {AcubeSATParameters::ADCSFineSunSensorFilteredTopLeft, AcubeSATParameters::adcsFineSunSensorFilteredTopLeft},
                  {AcubeSATParameters::ADCSFineSunSensorFilteredTopRight, AcubeSATParameters::adcsFineSunSensorFilteredTopRight},
                  {AcubeSATParameters::ADCSFineSunSensorFilteredBottomLeft, AcubeSATParameters::adcsFineSunSensorFilteredBottomLeft},
                  {AcubeSATParameters::ADCSFineSunSensorFilteredBottomRight, AcubeSATParameters::adcsFineSunSensorFilteredBottomRight},
                  {AcubeSATParameters::ADCSFineSunSensorAngularAlphaAngle, AcubeSATParameters::adcsFineSunSensorAngularAlphaAngle},
                  {AcubeSATParameters::ADCSFineSunSensorAngularBetaAngle, AcubeSATParameters::adcsFineSunSensorAngularBetaAngle},
                  {AcubeSATParameters::ADCSFineSunSensorCalculatedX, AcubeSATParameters::adcsFineSunSensorCalculatedX},
                  {AcubeSATParameters::ADCSFineSunSensorCalculatedY, AcubeSATParameters::adcsFineSunSensorCalculatedY},
                  {AcubeSATParameters::ADCSFineSunSensorCalculatedZ, AcubeSATParameters::adcsFineSunSensorCalculatedZ},
                  {AcubeSATParameters::ADCSGyroscopeRateX, AcubeSATParameters::adcsGyroscopeRateX},
                  {AcubeSATParameters::ADCSGyroscopeRateY, AcubeSATParameters::adcsGyroscopeRateY},
                  {AcubeSATParameters::ADCSGyroscopeRateZ, AcubeSATParameters::adcsGyroscopeRateZ},
                  {AcubeSATParameters::ADCSGyroXLOCSTRegister, AcubeSATParameters::adcsGyroXLOCSTRegister},
                  {AcubeSATParameters::ADCSGyroXHICSTRegister, AcubeSATParameters::adcsGyroXHICSTRegister},
                  {AcubeSATParameters::ADCSGyroXQUADRegister, AcubeSATParameters::adcsGyroXQUADRegister},
                  {AcubeSATParameters::ADCSGyroXFAULTRegister, AcubeSATParameters::adcsGyroXFAULTRegister},
                  {AcubeSATParameters::ADCSGyroYLOCSTRegister, AcubeSATParameters::adcsGyroYLOCSTRegister},
                  {AcubeSATParameters::ADCSGyroYHICSTRegister, AcubeSATParameters::adcsGyroYHICSTRegister},
                  {AcubeSATParameters::ADCSGyroYQUADRegister, AcubeSATParameters::adcsGyroYQUADRegister},
                  {AcubeSATParameters::ADCSGyroYFAULTRegister, AcubeSATParameters::adcsGyroYFAULTRegister},
                  {AcubeSATParameters::ADCSGyroZLOCSTRegister, AcubeSATParameters::adcsGyroZLOCSTRegister},
                  {AcubeSATParameters::ADCSGyroZHICSTRegister, AcubeSATParameters::adcsGyroZHICSTRegister},
                  {AcubeSATParameters::ADCSGyroZQUADRegister, AcubeSATParameters::adcsGyroZQUADRegister},
                  {AcubeSATParameters::ADCSGyroZFAULTRegister, AcubeSATParameters::adcsGyroZFAULTRegister},
                  {AcubeSATParameters::ADCSMagnetorquerOnXAxisHBridgePolarity, AcubeSATParameters::adcsMagnetorquerOnXAxisHBridgePolarity},
                  {AcubeSATParameters::ADCSMagnetorquerOnYAxisHBridgePolarity, AcubeSATParameters::adcsMagnetorquerOnYAxisHBridgePolarity},
                  {AcubeSATParameters::ADCSMagnetorquerOnZAxisHBridgePolarity, AcubeSATParameters::adcsMagnetorquerOnZAxisHBridgePolarity},
                  {AcubeSATParameters::ADCSMagnetorquerOnXAxisOnOff, AcubeSATParameters::adcsMagnetorquerOnXAxisOnOff},
                  {AcubeSATParameters::ADCSMagnetorquerOnYAxisOnOff, AcubeSATParameters::adcsMagnetorquerOnYAxisOnOff},
                  {AcubeSATParameters::ADCSMagnetorquerOnZAxisOnOff, AcubeSATParameters::adcsMagnetorquerOnZAxisOnOff},
                  {AcubeSATParameters::ADCSGainBdotXAxis, AcubeSATParameters::adcsGainBdotXAxis},
                  {AcubeSATParameters::ADCSGainBdotYAxis, AcubeSATParameters::adcsGainBdotYAxis},
                  {AcubeSATParameters::ADCSGainBdotZAxis, AcubeSATParameters::adcsGainBdotZAxis},
                  {AcubeSATParameters::ADCSGainProportionalPDXAxis, AcubeSATParameters::adcsGainProportionalPDXAxis},
                  {AcubeSATParameters::ADCSGainProportionalPDYAxis, AcubeSATParameters::adcsGainProportionalPDYAxis},
                  {AcubeSATParameters::ADCSGainProportionalPDZAxis, AcubeSATParameters::adcsGainProportionalPDZAxis},
                  {AcubeSATParameters::ADCSGainDerivativePDXAxis, AcubeSATParameters::adcsGainDerivativePDXAxis},
                  {AcubeSATParameters::ADCSGainDerivativePDYAxis, AcubeSATParameters::adcsGainDerivativePDYAxis},
                  {AcubeSATParameters::ADCSGainDerivativePDZAxis, AcubeSATParameters::adcsGainDerivativePDZAxis},
                  {AcubeSATParameters::ADCSiMQTBoardCoilXTemperatureSensor, AcubeSATParameters::adcsiMQTBoardCoilXTemperatureSensor},
                  {AcubeSATParameters::ADCSiMQTBoardCoilYTemperatureSensor, AcubeSATParameters::adcsiMQTBoardCoilYTemperatureSensor},
                  {AcubeSATParameters::ADCSiMQTBoardCoilZTemperatureSensor, AcubeSATParameters::adcsiMQTBoardCoilZTemperatureSensor},
                  {AcubeSATParameters::ADCSiMQTBoardExtraTemperatureSensor, AcubeSATParameters::adcsiMQTBoardExtraTemperatureSensor},
                  {AcubeSATParameters::ADCSGyroscopeXTemperature, AcubeSATParameters::adcsGyroscopeXTemperature},
                  {AcubeSATParameters::ADCSGyroscopeYTemperature, AcubeSATParameters::adcsGyroscopeYTemperature},
                  {AcubeSATParameters::ADCSGyroscopeZTemperature, AcubeSATParameters::adcsGyroscopeZTemperature},
                  {AcubeSATParameters::ADCSBoardTemperature1, AcubeSATParameters::adcsBoardTemperature1},
                  {AcubeSATParameters::ADCSBoardTemperature2, AcubeSATParameters::adcsBoardTemperature2},
                  {AcubeSATParameters::ADCSMode, AcubeSATParameters::adcsMode},
                  {AcubeSATParameters::ADCSTLE, AcubeSATParameters::adcsTLE},
                  {AcubeSATParameters::ADCSInitialKalmanQuaternionECIFrameToBodyScalar, AcubeSATParameters::adcsInitialKalmanQuaternionECIFrameToBodyScalar},
                  {AcubeSATParameters::ADCSInitialKalmanQuaternionECIFrameToBodyVectorElem1, AcubeSATParameters::adcsInitialKalmanQuaternionECIFrameToBodyVectorElem1},
                  {AcubeSATParameters::ADCSInitialKalmanQuaternionECIFrameToBodyVectorElem2, AcubeSATParameters::adcsInitialKalmanQuaternionECIFrameToBodyVectorElem2},
                  {AcubeSATParameters::ADCSInitialKalmanQuaternionECIFrameToBodyVectorElem3, AcubeSATParameters::adcsInitialKalmanQuaternionECIFrameToBodyVectorElem3},
                  {AcubeSATParameters::ADCSTLEOrbitalElementsArgumentPerigee, AcubeSATParameters::adcsTLEOrbitalElementsArgumentPerigee},
                  {AcubeSATParameters::ADCSTLEOrbitalElementsRAAN, AcubeSATParameters::adcsTLEOrbitalElementsRAAN},
                  {AcubeSATParameters::ADCSTLEOrbitalElementsInclination, AcubeSATParameters::adcsTLEOrbitalElementsInclination},
                  {AcubeSATParameters::ADCSTLEOrbitalElementsEccentricity, AcubeSATParameters::adcsTLEOrbitalElementsEccentricity},
                  {AcubeSATParameters::ADCSTLEOrbitalElementsMeanAnomaly, AcubeSATParameters::adcsTLEOrbitalElementsMeanAnomaly},
                  {AcubeSATParameters::ADCSSGP4OrbitalElementsArgumentPerigee, AcubeSATParameters::adcsSGP4OrbitalElementsArgumentPerigee},
                  {AcubeSATParameters::ADCSSGP4OrbitalElementsRAAN, AcubeSATParameters::adcsSGP4OrbitalElementsRAAN},
                  {AcubeSATParameters::ADCSSGP4OrbitalElementsInclination, AcubeSATParameters::adcsSGP4OrbitalElementsInclination},
                  {AcubeSATParameters::ADCSSGP4OrbitalElementsMeanAnomaly, AcubeSATParameters::adcsSGP4OrbitalElementsMeanAnomaly},
                  {AcubeSATParameters::ADCSTimeGST_JD, AcubeSATParameters::adcsTimeGST_JD},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ1, AcubeSATParameters::adcsDeterminationInitialMatricesQ1},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ2, AcubeSATParameters::adcsDeterminationInitialMatricesQ2},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ3, AcubeSATParameters::adcsDeterminationInitialMatricesQ3},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ4, AcubeSATParameters::adcsDeterminationInitialMatricesQ4},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ5, AcubeSATParameters::adcsDeterminationInitialMatricesQ5},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ6, AcubeSATParameters::adcsDeterminationInitialMatricesQ6},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ7, AcubeSATParameters::adcsDeterminationInitialMatricesQ7},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ8, AcubeSATParameters::adcsDeterminationInitialMatricesQ8},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ9, AcubeSATParameters::adcsDeterminationInitialMatricesQ9},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesQ10, AcubeSATParameters::adcsDeterminationInitialMatricesQ10},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR1, AcubeSATParameters::adcsDeterminationInitialMatricesR1},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR2, AcubeSATParameters::adcsDeterminationInitialMatricesR2},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR3, AcubeSATParameters::adcsDeterminationInitialMatricesR3},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR4, AcubeSATParameters::adcsDeterminationInitialMatricesR4},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR5, AcubeSATParameters::adcsDeterminationInitialMatricesR5},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR6, AcubeSATParameters::adcsDeterminationInitialMatricesR6},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR7, AcubeSATParameters::adcsDeterminationInitialMatricesR7},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR8, AcubeSATParameters::adcsDeterminationInitialMatricesR8},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesR9, AcubeSATParameters::adcsDeterminationInitialMatricesR9},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial1, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial1},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial2, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial2},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial3, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial3},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial4, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial4},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial5, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial5},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial6, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial6},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial7, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial7},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial8, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial8},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial9, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial9},
                  {AcubeSATParameters::ADCSDeterminationInitialMatricesPInitial10, AcubeSATParameters::adcsDeterminationInitialMatricesPInitial10},
                  {AcubeSATParameters::ADCSReactionWheelOn, AcubeSATParameters::adcsReactionWheelOn},
                  {AcubeSATParameters::ADCSReactionWheelAngularVelocity, AcubeSATParameters::adcsReactionWheelAngularVelocity},
                  {AcubeSATParameters::ADCSMagnetorquerAxisAssignment, AcubeSATParameters::adcsMagnetorquerAxisAssignment},
                  {AcubeSATParameters::ADCSControlProfileSwitching, AcubeSATParameters::adcsControlProfileSwitching},
                  {AcubeSATParameters::ADCSTransformationAxisXAssignment, AcubeSATParameters::adcsTransformationAxisXAssignment},
                  {AcubeSATParameters::ADCSTransformationAxisYAssignment, AcubeSATParameters::adcsTransformationAxisYAssignment},
                  {AcubeSATParameters::ADCSTransformationAxisZAssignment, AcubeSATParameters::adcsTransformationAxisZAssignment},
                  {AcubeSATParameters::ADCSMagnetometerAxisAssignment, AcubeSATParameters::adcsMagnetometerAxisAssignment},
                  {AcubeSATParameters::ADCSSunSensorAxisAssignment, AcubeSATParameters::adcsSunSensorAxisAssignment},
                  {AcubeSATParameters::ADCSGyroscopeAxisAssignment, AcubeSATParameters::adcsGyroscopeAxisAssignment},
                  {AcubeSATParameters::ADCSFrameAxisSignECIToECEF_X, AcubeSATParameters::adcsFrameAxisSignECIToECEF_X},
                  {AcubeSATParameters::ADCSFrameAxisSignECIToECEF_Y, AcubeSATParameters::adcsFrameAxisSignECIToECEF_Y},
                  {AcubeSATParameters::ADCSFrameAxisSignECIToECEF_Z, AcubeSATParameters::adcsFrameAxisSignECIToECEF_Z},
                  {AcubeSATParameters::ADCSFrameAxisSignECIToOrbit_X, AcubeSATParameters::adcsFrameAxisSignECIToOrbit_X},
                  {AcubeSATParameters::ADCSFrameAxisSignECIToOrbit_Y, AcubeSATParameters::adcsFrameAxisSignECIToOrbit_Y},
                  {AcubeSATParameters::ADCSFrameAxisSignECIToOrbit_Z, AcubeSATParameters::adcsFrameAxisSignECIToOrbit_Z},
                  {AcubeSATParameters::ADCSFrameAxisSignNEDToECEF_X, AcubeSATParameters::adcsFrameAxisSignNEDToECEF_X},
                  {AcubeSATParameters::ADCSFrameAxisSignNEDToECEF_Y, AcubeSATParameters::adcsFrameAxisSignNEDToECEF_Y},
                  {AcubeSATParameters::ADCSFrameAxisSignNEDToECEF_Z, AcubeSATParameters::adcsFrameAxisSignNEDToECEF_Z},
                  {AcubeSATParameters::ADCSMagnetometerSignX, AcubeSATParameters::adcsMagnetometerSignX},
                  {AcubeSATParameters::ADCSMagnetometerSignY, AcubeSATParameters::adcsMagnetometerSignY},
                  {AcubeSATParameters::ADCSMagnetometerSignZ, AcubeSATParameters::adcsMagnetometerSignZ},
                  {AcubeSATParameters::ADCSSunSensorXAxisSign, AcubeSATParameters::adcsSunSensorXAxisSign},
                  {AcubeSATParameters::ADCSSunSensorYAxisSign, AcubeSATParameters::adcsSunSensorYAxisSign},
                  {AcubeSATParameters::ADCSSunSensorZAxisSign, AcubeSATParameters::adcsSunSensorZAxisSign},
                  {AcubeSATParameters::ADCSGyroSignX, AcubeSATParameters::adcsGyroSignX},
                  {AcubeSATParameters::ADCSGyroSignY, AcubeSATParameters::adcsGyroSignY},
                  {AcubeSATParameters::ADCSGyroSignZ, AcubeSATParameters::adcsGyroSignZ},
                  {AcubeSATParameters::ADCSDetumblingNominalThresholds, AcubeSATParameters::adcsDetumblingNominalThresholds},
                  {AcubeSATParameters::ADCSNominalDetumblingThresholds, AcubeSATParameters::adcsNominalDetumblingThresholds},
                  {AcubeSATParameters::ADCSStandByDetumblingThresholds, AcubeSATParameters::adcsStandByDetumblingThresholds},
                  {AcubeSATParameters::ADCSDetumblingStandByThresholds, AcubeSATParameters::adcsDetumblingStandByThresholds},
                  {AcubeSATParameters::ADCSNominalStandByThresholds, AcubeSATParameters::adcsNominalStandByThresholds},
                  {AcubeSATParameters::ADCSMagnetorquerMagneticDipoleX, AcubeSATParameters::adcsMagnetorquerMagneticDipoleX},
                  {AcubeSATParameters::ADCSMagnetorquerMagneticDipoleY, AcubeSATParameters::adcsMagnetorquerMagneticDipoleY},
                  {AcubeSATParameters::ADCSMagnetorquerMagneticDipoleZ, AcubeSATParameters::adcsMagnetorquerMagneticDipoleZ},
                  {AcubeSATParameters::ADCSMagnetorquerDutyCycle, AcubeSATParameters::adcsMagnetorquerDutyCycle},
                  {AcubeSATParameters::ADCSMagnetorquerCurrentX, AcubeSATParameters::adcsMagnetorquerCurrentX},
                  {AcubeSATParameters::ADCSMagnetorquerCurrentY, AcubeSATParameters::adcsMagnetorquerCurrentY},
                  {AcubeSATParameters::ADCSMagnetorquerCurrentZ, AcubeSATParameters::adcsMagnetorquerCurrentZ},
                  {AcubeSATParameters::ADCSMagnetorquerBDot, AcubeSATParameters::adcsMagnetorquerBDot},
                  {AcubeSATParameters::ADCSReactionWheelTorque, AcubeSATParameters::adcsReactionWheelTorque},
                  {AcubeSATParameters::ADCSReactionWheelAngularAcceleration, AcubeSATParameters::adcsReactionWheelAngularAcceleration},
                  {AcubeSATParameters::ADCSDesiredQuaternionOrbitToBodyScalar, AcubeSATParameters::adcsDesiredQuaternionOrbitToBodyScalar},
                  {AcubeSATParameters::ADCSDesiredQuaternionVectorElem1, AcubeSATParameters::adcsDesiredQuaternionVectorElem1},
                  {AcubeSATParameters::ADCSDesiredQuaternionVectorElem2, AcubeSATParameters::adcsDesiredQuaternionVectorElem2},
                  {AcubeSATParameters::ADCSDesiredQuaternionVectorElem3, AcubeSATParameters::adcsDesiredQuaternionVectorElem3},
                  {AcubeSATParameters::ADCSAngularVelocityDesiredX, AcubeSATParameters::adcsAngularVelocityDesiredX},
                  {AcubeSATParameters::ADCSAngularVelocityDesiredY, AcubeSATParameters::adcsAngularVelocityDesiredY},
                  {AcubeSATParameters::ADCSAngularVelocityDesiredZ, AcubeSATParameters::adcsAngularVelocityDesiredZ},
                  {AcubeSATParameters::ADCSGyroBiasX, AcubeSATParameters::adcsGyroBiasX},
                  {AcubeSATParameters::ADCSGyroBiasY, AcubeSATParameters::adcsGyroBiasY},
                  {AcubeSATParameters::ADCSGyroBiasZ, AcubeSATParameters::adcsGyroBiasZ},
                  {AcubeSATParameters::ADCSSatellitePositionLatitude, AcubeSATParameters::adcsSatellitePositionLatitude},
                  {AcubeSATParameters::ADCSSatellitePositionLongitude, AcubeSATParameters::adcsSatellitePositionLongitude},
                  {AcubeSATParameters::ADCSSatellitePositionHeight, AcubeSATParameters::adcsSatellitePositionHeight},
                  {AcubeSATParameters::ADCSSatellitePositionECIX, AcubeSATParameters::adcsSatellitePositionECIX},
                  {AcubeSATParameters::ADCSSatellitePositionECIY, AcubeSATParameters::adcsSatellitePositionECIY},
                  {AcubeSATParameters::ADCSSatellitePositionECIZ, AcubeSATParameters::adcsSatellitePositionECIZ},
                  {AcubeSATParameters::ADCSSatelliteLinearVelocityECIX, AcubeSATParameters::adcsSatelliteLinearVelocityECIX},
                  {AcubeSATParameters::ADCSSatelliteLinearVelocityECIY, AcubeSATParameters::adcsSatelliteLinearVelocityECIY},
                  {AcubeSATParameters::ADCSSatelliteLinearVelocityECIZ, AcubeSATParameters::adcsSatelliteLinearVelocityECIZ},
                  {AcubeSATParameters::ADCSMagneticFieldNEDX, AcubeSATParameters::adcsMagneticFieldNEDX},
                  {AcubeSATParameters::ADCSMagneticFieldNEDY, AcubeSATParameters::adcsMagneticFieldNEDY},
                  {AcubeSATParameters::ADCSMagneticFieldNEDZ, AcubeSATParameters::adcsMagneticFieldNEDZ},
                  {AcubeSATParameters::ADCSMagneticFieldECIX, AcubeSATParameters::adcsMagneticFieldECIX},
                  {AcubeSATParameters::ADCSMagneticFieldECIY, AcubeSATParameters::adcsMagneticFieldECIY},
                  {AcubeSATParameters::ADCSMagneticFieldECIZ, AcubeSATParameters::adcsMagneticFieldECIZ},
                  {AcubeSATParameters::ADCSSunPositionECIX, AcubeSATParameters::adcsSunPositionECIX},
                  {AcubeSATParameters::ADCSSunPositionECIY, AcubeSATParameters::adcsSunPositionECIY},
                  {AcubeSATParameters::ADCSSunPositionECIZ, AcubeSATParameters::adcsSunPositionECIZ},
                  {AcubeSATParameters::ADCSEclipse, AcubeSATParameters::adcsEclipse},
                  {AcubeSATParameters::ADCSDesaturationPecentageParameter, AcubeSATParameters::adcsDesaturationPecentageParameter},
                  {AcubeSATParameters::ADCSISISMTQModes, AcubeSATParameters::adcsISISMTQModes},
                  {AcubeSATParameters::ADCSMagnetorquerActuationMethod, AcubeSATParameters::adcsMagnetorquerActuationMethod},
                  {AcubeSATParameters::ADCSDutyCycleDetermination, AcubeSATParameters::adcsDutyCycleDetermination},
                  {AcubeSATParameters::ADCSDutyCycleControl, AcubeSATParameters::adcsDutyCycleControl},
                  {AcubeSATParameters::ADCSDutyCycleOther, AcubeSATParameters::adcsDutyCycleOther},
                  {AcubeSATParameters::ADCSDesatInitialAngularVelocityParam, AcubeSATParameters::adcsDesatInitialAngularVelocityParam},
                  {AcubeSATParameters::ADCSMCUInputVoltage, AcubeSATParameters::adcsMCUInputVoltage},
                  {AcubeSATParameters::ADCSMemoryPartition, AcubeSATParameters::adcsMemoryPartition},
                  {AcubeSATParameters::ADCSLastFailedEvent, AcubeSATParameters::adcsLastFailedEvent},
                  {AcubeSATParameters::ADCSRAMScrubbingFrequency, AcubeSATParameters::adcsRAMScrubbingFrequency},
                  {AcubeSATParameters::ADCSProgramFlashScrubbingFrequency, AcubeSATParameters::adcsProgramFlashScrubbingFrequency},
                  {AcubeSATParameters::ADCSFLASHInt, AcubeSATParameters::adcsFlashInt},
                  {AcubeSATParameters::ADCSSRAMInt, AcubeSATParameters::adcsSRAMInt},
                  //---------------------------------------------------------------------------------------------
                  {AcubeSATParameters::EPS_MODE,    AcubeSATParameters::epsMODE},
                  {AcubeSATParameters::EPS_CONF,    AcubeSATParameters::epsCONF},
                  {AcubeSATParameters::EPS_RESET_CAUSE,AcubeSATParameters::epsRESET_CAUSE},
                  {AcubeSATParameters::EPS_UPTIME,  AcubeSATParameters::epsUPTIME},
                  {AcubeSATParameters::EPS_ERROR,   AcubeSATParameters::epsERROR},
                  {AcubeSATParameters::EPS_RC_CNT_PWRON,AcubeSATParameters::epsRC_CNT_PWRON},
                  {AcubeSATParameters::EPS_RC_CNT_WDG,AcubeSATParameters::epsRC_CNT_WDG},
                  {AcubeSATParameters::EPS_RC_CNT_CMD,AcubeSATParameters::epsRC_CNT_CMD},
                  {AcubeSATParameters::EPS_RC_CNT_MCU,AcubeSATParameters::epsRC_CNT_MCU},
                  {AcubeSATParameters::EPS_RC_CNT_EMLOPO,AcubeSATParameters::epsRC_CNT_EMLOPO},
                  {AcubeSATParameters::EPS_PREVCMD_ELAPSED,AcubeSATParameters::epsPREVCMD_ELAPSED},
                  {AcubeSATParameters::EPS_UNIX_TIME,AcubeSATParameters::epsUNIX_TIME},
                  {AcubeSATParameters::EPS_UNIX_YEAR,AcubeSATParameters::epsUNIX_YEAR},
                  {AcubeSATParameters::EPS_UNIX_MONTH,AcubeSATParameters::epsUNIX_MONTH},
                  {AcubeSATParameters::EPS_UNIX_DAY,AcubeSATParameters::epsUNIX_DAY},
                  {AcubeSATParameters::EPS_UNIX_HOUR,AcubeSATParameters::epsUNIX_HOUR},
                  {AcubeSATParameters::EPS_UNIX_MINUTE,AcubeSATParameters::epsUNIX_MINUTE},
                  {AcubeSATParameters::EPS_UNIX_SECOND,AcubeSATParameters::epsUNIX_SECOND},
                  {AcubeSATParameters::EPS_STAT_CH_ON,AcubeSATParameters::epsSTAT_CH_ON},
                  {AcubeSATParameters::EPS_STAT_CH_EXT_ON,AcubeSATParameters::epsSTAT_CH_EXT_ON},
                  {AcubeSATParameters::EPS_STAT_CH_OCF,AcubeSATParameters::epsSTAT_CH_OCF},
                  {AcubeSATParameters::EPS_STAT_CH_EXT_OCF,AcubeSATParameters::epsSTAT_CH_EXT_OCF},
                  {AcubeSATParameters::EPS_OCF_CNT_CH00,AcubeSATParameters::epsOCF_CNT_CH00},
                  {AcubeSATParameters::EPS_OCF_CNT_CH01,AcubeSATParameters::epsOCF_CNT_CH01},
                  {AcubeSATParameters::EPS_OCF_CNT_CH02,AcubeSATParameters::epsOCF_CNT_CH02},
                  {AcubeSATParameters::EPS_OCF_CNT_CH03,AcubeSATParameters::epsOCF_CNT_CH03},
                  {AcubeSATParameters::EPS_OCF_CNT_CH04,AcubeSATParameters::epsOCF_CNT_CH04},
                  {AcubeSATParameters::EPS_OCF_CNT_CH05,AcubeSATParameters::epsOCF_CNT_CH05},
                  {AcubeSATParameters::EPS_OCF_CNT_CH06,AcubeSATParameters::epsOCF_CNT_CH06},
                  {AcubeSATParameters::EPS_OCF_CNT_CH07,AcubeSATParameters::epsOCF_CNT_CH07},
                  {AcubeSATParameters::EPS_OCF_CNT_CH08,AcubeSATParameters::epsOCF_CNT_CH08},
                  {AcubeSATParameters::EPS_OCF_CNT_CH09,AcubeSATParameters::epsOCF_CNT_CH09},
                  {AcubeSATParameters::EPS_OCF_CNT_CH10,AcubeSATParameters::epsOCF_CNT_CH10},
                  {AcubeSATParameters::EPS_OCF_CNT_CH11,AcubeSATParameters::epsOCF_CNT_CH11},
                  {AcubeSATParameters::EPS_OCF_CNT_CH12,AcubeSATParameters::epsOCF_CNT_CH12},
                  {AcubeSATParameters::EPS_OCF_CNT_CH13,AcubeSATParameters::epsOCF_CNT_CH13},
                  {AcubeSATParameters::EPS_OCF_CNT_CH14,AcubeSATParameters::epsOCF_CNT_CH14},
                  {AcubeSATParameters::EPS_OCF_CNT_CH15,AcubeSATParameters::epsOCF_CNT_CH15},
                  {AcubeSATParameters::EPS_ABF_PLACED_0,AcubeSATParameters::epsABF_PLACED_0},
                  {AcubeSATParameters::EPS_ABF_PLACED_1,AcubeSATParameters::epsABF_PLACED_1},
                  {AcubeSATParameters::EPS_VOLT_BRDSUP_RAW,AcubeSATParameters::epsVOLT_BRDSUP_RAW},
                  {AcubeSATParameters::EPS_TEMP_MCU_RAW,AcubeSATParameters::epsTEMP_MCU_RAW},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD0_RAW,AcubeSATParameters::epsVIP_VOLT_VD0_RAW},
                  {AcubeSATParameters::EPS_VIP_CURR_VD0_RAW,AcubeSATParameters::epsVIP_CURR_VD0_RAW},
                  {AcubeSATParameters::EPS_VIP_POWE_VD0_RAW,AcubeSATParameters::epsVIP_POWE_VD0_RAW},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD1_RAW,AcubeSATParameters::epsVIP_VOLT_VD1_RAW},
                  {AcubeSATParameters::EPS_VIP_CURR_VD1_RAW,AcubeSATParameters::epsVIP_CURR_VD1_RAW},
                  {AcubeSATParameters::EPS_VIP_POWE_VD1_RAW,AcubeSATParameters::epsVIP_POWE_VD1_RAW},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD2_RAW,AcubeSATParameters::epsVIP_VOLT_VD2_RAW},
                  {AcubeSATParameters::EPS_VIP_CURR_VD2_RAW,AcubeSATParameters::epsVIP_CURR_VD2_RAW},
                  {AcubeSATParameters::EPS_VIP_POWE_VD2_RAW,AcubeSATParameters::epsVIP_POWE_VD2_RAW},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD3_RAW,AcubeSATParameters::epsVIP_VOLT_VD3_RAW},
                  {AcubeSATParameters::EPS_VIP_CURR_VD3_RAW,AcubeSATParameters::epsVIP_CURR_VD3_RAW},
                  {AcubeSATParameters::EPS_VIP_POWE_VD3_RAW,AcubeSATParameters::epsVIP_POWE_VD3_RAW},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD4_RAW,AcubeSATParameters::epsVIP_VOLT_VD4_RAW},
                  {AcubeSATParameters::EPS_VIP_CURR_VD4_RAW,AcubeSATParameters::epsVIP_CURR_VD4_RAW},
                  {AcubeSATParameters::EPS_VIP_POWE_VD4_RAW,AcubeSATParameters::epsVIP_POWE_VD4_RAW},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD5_RAW,AcubeSATParameters::epsVIP_VOLT_VD5_RAW},
                  {AcubeSATParameters::EPS_VIP_CURR_VD5_RAW,AcubeSATParameters::epsVIP_CURR_VD5_RAW},
                  {AcubeSATParameters::EPS_VIP_POWE_VD5_RAW,AcubeSATParameters::epsVIP_POWE_VD5_RAW},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD6_RAW,AcubeSATParameters::epsVIP_VOLT_VD6_RAW},
                  {AcubeSATParameters::EPS_VIP_CURR_VD6_RAW,AcubeSATParameters::epsVIP_CURR_VD6_RAW},
                  {AcubeSATParameters::EPS_VIP_POWE_VD6_RAW,AcubeSATParameters::epsVIP_POWE_VD6_RAW},
                  {AcubeSATParameters::EPS_VOLT_BRDSUP_ENG,AcubeSATParameters::epsVOLT_BRDSUP_ENG},
                  {AcubeSATParameters::EPS_TEMP_MCU_ENG,AcubeSATParameters::epsTEMP_MCU_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_INPUT_ENG,AcubeSATParameters::epsVIP_VOLT_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_INPUT_ENG,AcubeSATParameters::epsVIP_CURR_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_INPUT_ENG,AcubeSATParameters::epsVIP_POWE_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_DIST_INPUT_ENG,AcubeSATParameters::epsVIP_VOLT_DIST_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_DIST_INPUT_ENG,AcubeSATParameters::epsVIP_CURR_DIST_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_DIST_INPUT_ENG,AcubeSATParameters::epsVIP_POWE_DIST_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_BAT_INPUT_ENG,AcubeSATParameters::epsVIP_VOLT_BAT_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_BAT_INPUT_ENG,AcubeSATParameters::epsVIP_CURR_BAT_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_BAT_INPUT_ENG,AcubeSATParameters::epsVIP_POWE_BAT_INPUT_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD0_ENG,AcubeSATParameters::epsVIP_VOLT_VD0_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_VD0_ENG,AcubeSATParameters::epsVIP_CURR_VD0_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_VD0_ENG,AcubeSATParameters::epsVIP_POWE_VD0_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD1_ENG,AcubeSATParameters::epsVIP_VOLT_VD1_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_VD1_ENG,AcubeSATParameters::epsVIP_CURR_VD1_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_VD1_ENG,AcubeSATParameters::epsVIP_POWE_VD1_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD2_ENG,AcubeSATParameters::epsVIP_VOLT_VD2_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_VD2_ENG,AcubeSATParameters::epsVIP_CURR_VD2_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_VD2_ENG,AcubeSATParameters::epsVIP_POWE_VD2_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD3_ENG,AcubeSATParameters::epsVIP_VOLT_VD3_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_VD3_ENG,AcubeSATParameters::epsVIP_CURR_VD3_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_VD3_ENG,AcubeSATParameters::epsVIP_POWE_VD3_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD4_ENG,AcubeSATParameters::epsVIP_VOLT_VD4_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_VD4_ENG,AcubeSATParameters::epsVIP_CURR_VD4_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_VD4_ENG,AcubeSATParameters::epsVIP_POWE_VD4_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD5_ENG,AcubeSATParameters::epsVIP_VOLT_VD5_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_VD5_ENG,AcubeSATParameters::epsVIP_CURR_VD5_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_VD5_ENG,AcubeSATParameters::epsVIP_POWE_VD5_ENG},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD6_ENG,AcubeSATParameters::epsVIP_VOLT_VD6_ENG},
                  {AcubeSATParameters::EPS_VIP_CURR_VD6_ENG,AcubeSATParameters::epsVIP_CURR_VD6_ENG},
                  {AcubeSATParameters::EPS_VIP_POWE_VD6_ENG,AcubeSATParameters::epsVIP_POWE_VD6_ENG},
                  {AcubeSATParameters::EPS_VOLT_BRDSUP_RA,AcubeSATParameters::epsVOLT_BRDSUP_RA},
                  {AcubeSATParameters::EPS_TEMP_MCU_RA,AcubeSATParameters::epsTEMP_MCU_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_INPUT_RA,AcubeSATParameters::epsVIP_VOLT_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_INPUT_RA,AcubeSATParameters::epsVIP_CURR_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_INPUT_RA,AcubeSATParameters::epsVIP_POWE_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_DIST_INPUT_RA,AcubeSATParameters::epsVIP_VOLT_DIST_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_DIST_INPUT_RA,AcubeSATParameters::epsVIP_CURR_DIST_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_DIST_INPUT_RA,AcubeSATParameters::epsVIP_POWE_DIST_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_BAT_INPUT_RA,AcubeSATParameters::epsVIP_VOLT_BAT_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_BAT_INPUT_RA,AcubeSATParameters::epsVIP_CURR_BAT_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_BAT_INPUT_RA,AcubeSATParameters::epsVIP_POWE_BAT_INPUT_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD0_RA,AcubeSATParameters::epsVIP_VOLT_VD0_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_VD0_RA,AcubeSATParameters::epsVIP_CURR_VD0_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_VD0_RA,AcubeSATParameters::epsVIP_POWE_VD0_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD1_RA,AcubeSATParameters::epsVIP_VOLT_VD1_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_VD1_RA,AcubeSATParameters::epsVIP_CURR_VD1_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_VD1_RA,AcubeSATParameters::epsVIP_POWE_VD1_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD2_RA,AcubeSATParameters::epsVIP_VOLT_VD2_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_VD2_RA,AcubeSATParameters::epsVIP_CURR_VD2_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_VD2_RA,AcubeSATParameters::epsVIP_POWE_VD2_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD3_RA,AcubeSATParameters::epsVIP_VOLT_VD3_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_VD3_RA,AcubeSATParameters::epsVIP_CURR_VD3_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_VD3_RA,AcubeSATParameters::epsVIP_POWE_VD3_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD4_RA,AcubeSATParameters::epsVIP_VOLT_VD4_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_VD4_RA,AcubeSATParameters::epsVIP_CURR_VD4_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_VD4_RA,AcubeSATParameters::epsVIP_POWE_VD4_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD5_RA,AcubeSATParameters::epsVIP_VOLT_VD5_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_VD5_RA,AcubeSATParameters::epsVIP_CURR_VD5_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_VD5_RA,AcubeSATParameters::epsVIP_POWE_VD5_RA},
                  {AcubeSATParameters::EPS_VIP_VOLT_VD6_RA,AcubeSATParameters::epsVIP_VOLT_VD6_RA},
                  {AcubeSATParameters::EPS_VIP_CURR_VD6_RA,AcubeSATParameters::epsVIP_CURR_VD6_RA},
                  {AcubeSATParameters::EPS_VIP_POWE_VD6_RA,AcubeSATParameters::epsVIP_POWE_VD6_RA},
                  {AcubeSATParameters::EPS_STAT_BU, AcubeSATParameters::epsSTAT_BU},
                  {AcubeSATParameters::EPS_VOLT_BP1_INPUT_RAW,AcubeSATParameters::epsVOLT_BP1_INPUT_RAW},
                  {AcubeSATParameters::EPS_CURR_BP1_INPUT_RAW,AcubeSATParameters::epsCURR_BP1_INPUT_RAW},
                  {AcubeSATParameters::EPS_POWE_BP1_INPUT_RAW,AcubeSATParameters::epsPOWE_BP1_INPUT_RAW},
                  {AcubeSATParameters::EPS_STAT_BP1_RAW,AcubeSATParameters::epsSTAT_BP1_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL1_RAW,AcubeSATParameters::epsVOLT_BP1_CELL1_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL2_RAW,AcubeSATParameters::epsVOLT_BP1_CELL2_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL3_RAW,AcubeSATParameters::epsVOLT_BP1_CELL3_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL4_RAW,AcubeSATParameters::epsVOLT_BP1_CELL4_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP1_RAW,AcubeSATParameters::epsBAT_TEMP1_BP1_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP1_RAW,AcubeSATParameters::epsBAT_TEMP2_BP1_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP1_RAW,AcubeSATParameters::epsBAT_TEMP3_BP1_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP2_INPUT_RAW,AcubeSATParameters::epsVOLT_BP2_INPUT_RAW},
                  {AcubeSATParameters::EPS_CURR_BP2_INPUT_RAW,AcubeSATParameters::epsCURR_BP2_INPUT_RAW},
                  {AcubeSATParameters::EPS_POWE_BP2_INPUT_RAW,AcubeSATParameters::epsPOWE_BP2_INPUT_RAW},
                  {AcubeSATParameters::EPS_STAT_BP2_RAW,AcubeSATParameters::epsSTAT_BP2_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL1_RAW,AcubeSATParameters::epsVOLT_BP2_CELL1_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL2_RAW,AcubeSATParameters::epsVOLT_BP2_CELL2_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL3_RAW,AcubeSATParameters::epsVOLT_BP2_CELL3_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL4_RAW,AcubeSATParameters::epsVOLT_BP2_CELL4_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP2_RAW,AcubeSATParameters::epsBAT_TEMP1_BP2_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP2_RAW,AcubeSATParameters::epsBAT_TEMP2_BP2_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP2_RAW,AcubeSATParameters::epsBAT_TEMP3_BP2_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP3_INPUT_RAW,AcubeSATParameters::epsVOLT_BP3_INPUT_RAW},
                  {AcubeSATParameters::EPS_CURR_BP3_INPUT_RAW,AcubeSATParameters::epsCURR_BP3_INPUT_RAW},
                  {AcubeSATParameters::EPS_POWE_BP3_INPUT_RAW,AcubeSATParameters::epsPOWE_BP3_INPUT_RAW},
                  {AcubeSATParameters::EPS_STAT_BP3_RAW,AcubeSATParameters::epsSTAT_BP3_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL1_RAW,AcubeSATParameters::epsVOLT_BP3_CELL1_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL2_RAW,AcubeSATParameters::epsVOLT_BP3_CELL2_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL3_RAW,AcubeSATParameters::epsVOLT_BP3_CELL3_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL4_RAW,AcubeSATParameters::epsVOLT_BP3_CELL4_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP3_RAW,AcubeSATParameters::epsBAT_TEMP1_BP3_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP3_RAW,AcubeSATParameters::epsBAT_TEMP2_BP3_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP3_RAW,AcubeSATParameters::epsBAT_TEMP3_BP3_RAW},
                  {AcubeSATParameters::EPS_VOLT_BP1_INPUT_ENG,AcubeSATParameters::epsVOLT_BP1_INPUT_ENG},
                  {AcubeSATParameters::EPS_CURR_BP1_INPUT_ENG,AcubeSATParameters::epsCURR_BP1_INPUT_ENG},
                  {AcubeSATParameters::EPS_POWE_BP1_INPUT_ENG,AcubeSATParameters::epsPOWE_BP1_INPUT_ENG},
                  {AcubeSATParameters::EPS_STAT_BP1_ENG,AcubeSATParameters::epsSTAT_BP1_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL1_ENG,AcubeSATParameters::epsVOLT_BP1_CELL1_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL2_ENG,AcubeSATParameters::epsVOLT_BP1_CELL2_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL3_ENG,AcubeSATParameters::epsVOLT_BP1_CELL3_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL4_ENG,AcubeSATParameters::epsVOLT_BP1_CELL4_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP1_ENG,AcubeSATParameters::epsBAT_TEMP1_BP1_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP1_ENG,AcubeSATParameters::epsBAT_TEMP2_BP1_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP1_ENG,AcubeSATParameters::epsBAT_TEMP3_BP1_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP2_INPUT_ENG,AcubeSATParameters::epsVOLT_BP2_INPUT_ENG},
                  {AcubeSATParameters::EPS_CURR_BP2_INPUT_ENG,AcubeSATParameters::epsCURR_BP2_INPUT_ENG},
                  {AcubeSATParameters::EPS_POWE_BP2_INPUT_ENG,AcubeSATParameters::epsPOWE_BP2_INPUT_ENG},
                  {AcubeSATParameters::EPS_STAT_BP2_ENG,AcubeSATParameters::epsSTAT_BP2_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL1_ENG,AcubeSATParameters::epsVOLT_BP2_CELL1_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL2_ENG,AcubeSATParameters::epsVOLT_BP2_CELL2_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL3_ENG,AcubeSATParameters::epsVOLT_BP2_CELL3_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL4_ENG,AcubeSATParameters::epsVOLT_BP2_CELL4_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP2_ENG,AcubeSATParameters::epsBAT_TEMP1_BP2_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP2_ENG,AcubeSATParameters::epsBAT_TEMP2_BP2_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP2_ENG,AcubeSATParameters::epsBAT_TEMP3_BP2_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP3_INPUT_ENG,AcubeSATParameters::epsVOLT_BP3_INPUT_ENG},
                  {AcubeSATParameters::EPS_CURR_BP3_INPUT_ENG,AcubeSATParameters::epsCURR_BP3_INPUT_ENG},
                  {AcubeSATParameters::EPS_POWE_BP3_INPUT_ENG,AcubeSATParameters::epsPOWE_BP3_INPUT_ENG},
                  {AcubeSATParameters::EPS_STAT_BP3_ENG,AcubeSATParameters::epsSTAT_BP3_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL1_ENG,AcubeSATParameters::epsVOLT_BP3_CELL1_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL2_ENG,AcubeSATParameters::epsVOLT_BP3_CELL2_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL3_ENG,AcubeSATParameters::epsVOLT_BP3_CELL3_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL4_ENG,AcubeSATParameters::epsVOLT_BP3_CELL4_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP3_ENG,AcubeSATParameters::epsBAT_TEMP1_BP3_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP3_ENG,AcubeSATParameters::epsBAT_TEMP2_BP3_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP3_ENG,AcubeSATParameters::epsBAT_TEMP3_BP3_ENG},
                  {AcubeSATParameters::EPS_VOLT_BP1_INPUT_RA,AcubeSATParameters::epsVOLT_BP1_INPUT_RA},
                  {AcubeSATParameters::EPS_CURR_BP1_INPUT_RA,AcubeSATParameters::epsCURR_BP1_INPUT_RA},
                  {AcubeSATParameters::EPS_POWE_BP1_INPUT_RA,AcubeSATParameters::epsPOWE_BP1_INPUT_RA},
                  {AcubeSATParameters::EPS_STAT_BP1_RA,AcubeSATParameters::epsSTAT_BP1_RA},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL1_RA,AcubeSATParameters::epsVOLT_BP1_CELL1_RA},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL2_RA,AcubeSATParameters::epsVOLT_BP1_CELL2_RA},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL3_RA,AcubeSATParameters::epsVOLT_BP1_CELL3_RA},
                  {AcubeSATParameters::EPS_VOLT_BP1_CELL4_RA,AcubeSATParameters::epsVOLT_BP1_CELL4_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP1_RA,AcubeSATParameters::epsBAT_TEMP1_BP1_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP1_RA,AcubeSATParameters::epsBAT_TEMP2_BP1_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP1_RA,AcubeSATParameters::epsBAT_TEMP3_BP1_RA},
                  {AcubeSATParameters::EPS_VOLT_BP2_INPUT_RA,AcubeSATParameters::epsVOLT_BP2_INPUT_RA},
                  {AcubeSATParameters::EPS_CURR_BP2_INPUT_RA,AcubeSATParameters::epsCURR_BP2_INPUT_RA},
                  {AcubeSATParameters::EPS_POWE_BP2_INPUT_RA,AcubeSATParameters::epsPOWE_BP2_INPUT_RA},
                  {AcubeSATParameters::EPS_STAT_BP2_RA,AcubeSATParameters::epsSTAT_BP2_RA},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL1_RA,AcubeSATParameters::epsVOLT_BP2_CELL1_RA},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL2_RA,AcubeSATParameters::epsVOLT_BP2_CELL2_RA},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL3_RA,AcubeSATParameters::epsVOLT_BP2_CELL3_RA},
                  {AcubeSATParameters::EPS_VOLT_BP2_CELL4_RA,AcubeSATParameters::epsVOLT_BP2_CELL4_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP2_RA,AcubeSATParameters::epsBAT_TEMP1_BP2_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP2_RA,AcubeSATParameters::epsBAT_TEMP2_BP2_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP2_RA,AcubeSATParameters::epsBAT_TEMP3_BP2_RA},
                  {AcubeSATParameters::EPS_VOLT_BP3_INPUT_RA,AcubeSATParameters::epsVOLT_BP3_INPUT_RA},
                  {AcubeSATParameters::EPS_CURR_BP3_INPUT_RA,AcubeSATParameters::epsCURR_BP3_INPUT_RA},
                  {AcubeSATParameters::EPS_POWE_BP3_INPUT_RA,AcubeSATParameters::epsPOWE_BP3_INPUT_RA},
                  {AcubeSATParameters::EPS_STAT_BP3_RA,AcubeSATParameters::epsSTAT_BP3_RA},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL1_RA,AcubeSATParameters::epsVOLT_BP3_CELL1_RA},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL2_RA,AcubeSATParameters::epsVOLT_BP3_CELL2_RA},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL3_RA,AcubeSATParameters::epsVOLT_BP3_CELL3_RA},
                  {AcubeSATParameters::EPS_VOLT_BP3_CELL4_RA,AcubeSATParameters::epsVOLT_BP3_CELL4_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP1_BP3_RA,AcubeSATParameters::epsBAT_TEMP1_BP3_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP2_BP3_RA,AcubeSATParameters::epsBAT_TEMP2_BP3_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP3_BP3_RA,AcubeSATParameters::epsBAT_TEMP3_BP3_RA},
                  {AcubeSATParameters::EPS_VOLT_VD0_RAW,AcubeSATParameters::epsVOLT_VD0_RAW},
                  {AcubeSATParameters::EPS_VOLT_VD1_RAW,AcubeSATParameters::epsVOLT_VD1_RAW},
                  {AcubeSATParameters::EPS_VOLT_VD2_RAW,AcubeSATParameters::epsVOLT_VD2_RAW},
                  {AcubeSATParameters::EPS_VOLT_VD0_ENG,AcubeSATParameters::epsVOLT_VD0_ENG},
                  {AcubeSATParameters::EPS_VOLT_VD1_ENG,AcubeSATParameters::epsVOLT_VD1_ENG},
                  {AcubeSATParameters::EPS_VOLT_VD2_ENG,AcubeSATParameters::epsVOLT_VD2_ENG},
                  {AcubeSATParameters::EPS_VOLT_VD0_RA,AcubeSATParameters::epsVOLT_VD0_RA},
                  {AcubeSATParameters::EPS_VOLT_VD1_RA,AcubeSATParameters::epsVOLT_VD1_RA},
                  {AcubeSATParameters::EPS_VOLT_VD2_RA,AcubeSATParameters::epsVOLT_VD2_RA},
                  {AcubeSATParameters::EPS_BAT_STAT,AcubeSATParameters::epsBAT_STAT},
                  {AcubeSATParameters::EPS_BAT_TEMP2_RAW,AcubeSATParameters::epsBAT_TEMP2_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP3_RAW,AcubeSATParameters::epsBAT_TEMP3_RAW},
                  {AcubeSATParameters::EPS_BAT_TEMP2_ENG,AcubeSATParameters::epsBAT_TEMP2_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP3_ENG,AcubeSATParameters::epsBAT_TEMP3_ENG},
                  {AcubeSATParameters::EPS_BAT_TEMP2_RA,AcubeSATParameters::epsBAT_TEMP2_RA},
                  {AcubeSATParameters::EPS_BAT_TEMP3_RA,AcubeSATParameters::epsBAT_TEMP3_RA},
                  {AcubeSATParameters::EPS_CC1_VOLT_IN_MPPT_RAW,AcubeSATParameters::epsCC1_VOLT_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC2_VOLT_IN_MPPT_RAW,AcubeSATParameters::epsCC2_VOLT_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC3_VOLT_IN_MPPT_RAW,AcubeSATParameters::epsCC3_VOLT_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC4_VOLT_IN_MPPT_RAW,AcubeSATParameters::epsCC4_VOLT_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC5_VOLT_IN_MPPT_RAW,AcubeSATParameters::epsCC5_VOLT_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC1_CURR_IN_MPPT_RAW,AcubeSATParameters::epsCC1_CURR_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC2_CURR_IN_MPPT_RAW,AcubeSATParameters::epsCC2_CURR_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC3_CURR_IN_MPPT_RAW,AcubeSATParameters::epsCC3_CURR_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC4_CURR_IN_MPPT_RAW,AcubeSATParameters::epsCC4_CURR_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC5_CURR_IN_MPPT_RAW,AcubeSATParameters::epsCC5_CURR_IN_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC1_VOLT_OU_MPPT_RAW,AcubeSATParameters::epsCC1_VOLT_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC2_VOLT_OU_MPPT_RAW,AcubeSATParameters::epsCC2_VOLT_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC3_VOLT_OU_MPPT_RAW,AcubeSATParameters::epsCC3_VOLT_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC4_VOLT_OU_MPPT_RAW,AcubeSATParameters::epsCC4_VOLT_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC5_VOLT_OU_MPPT_RAW,AcubeSATParameters::epsCC5_VOLT_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC1_CURR_OU_MPPT_RAW,AcubeSATParameters::epsCC1_CURR_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC2_CURR_OU_MPPT_RAW,AcubeSATParameters::epsCC2_CURR_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC3_CURR_OU_MPPT_RAW,AcubeSATParameters::epsCC3_CURR_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC4_CURR_OU_MPPT_RAW,AcubeSATParameters::epsCC4_CURR_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC5_CURR_OU_MPPT_RAW,AcubeSATParameters::epsCC5_CURR_OU_MPPT_RAW},
                  {AcubeSATParameters::EPS_CC1_VOLT_IN_MPPT_ENG,AcubeSATParameters::epsCC1_VOLT_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC2_VOLT_IN_MPPT_ENG,AcubeSATParameters::epsCC2_VOLT_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC3_VOLT_IN_MPPT_ENG,AcubeSATParameters::epsCC3_VOLT_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC4_VOLT_IN_MPPT_ENG,AcubeSATParameters::epsCC4_VOLT_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC5_VOLT_IN_MPPT_ENG,AcubeSATParameters::epsCC5_VOLT_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC1_CURR_IN_MPPT_ENG,AcubeSATParameters::epsCC1_CURR_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC2_CURR_IN_MPPT_ENG,AcubeSATParameters::epsCC2_CURR_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC3_CURR_IN_MPPT_ENG,AcubeSATParameters::epsCC3_CURR_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC4_CURR_IN_MPPT_ENG,AcubeSATParameters::epsCC4_CURR_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC5_CURR_IN_MPPT_ENG,AcubeSATParameters::epsCC5_CURR_IN_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC1_VOLT_OU_MPPT_ENG,AcubeSATParameters::epsCC1_VOLT_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC2_VOLT_OU_MPPT_ENG,AcubeSATParameters::epsCC2_VOLT_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC3_VOLT_OU_MPPT_ENG,AcubeSATParameters::epsCC3_VOLT_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC4_VOLT_OU_MPPT_ENG,AcubeSATParameters::epsCC4_VOLT_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC5_VOLT_OU_MPPT_ENG,AcubeSATParameters::epsCC5_VOLT_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC1_CURR_OU_MPPT_ENG,AcubeSATParameters::epsCC1_CURR_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC2_CURR_OU_MPPT_ENG,AcubeSATParameters::epsCC2_CURR_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC3_CURR_OU_MPPT_ENG,AcubeSATParameters::epsCC3_CURR_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC4_CURR_OU_MPPT_ENG,AcubeSATParameters::epsCC4_CURR_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC5_CURR_OU_MPPT_ENG,AcubeSATParameters::epsCC5_CURR_OU_MPPT_ENG},
                  {AcubeSATParameters::EPS_CC1_VOLT_IN_MPPT_RA,AcubeSATParameters::epsCC1_VOLT_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC2_VOLT_IN_MPPT_RA,AcubeSATParameters::epsCC2_VOLT_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC3_VOLT_IN_MPPT_RA,AcubeSATParameters::epsCC3_VOLT_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC4_VOLT_IN_MPPT_RA,AcubeSATParameters::epsCC4_VOLT_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC5_VOLT_IN_MPPT_RA,AcubeSATParameters::epsCC5_VOLT_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC1_CURR_IN_MPPT_RA,AcubeSATParameters::epsCC1_CURR_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC2_CURR_IN_MPPT_RA,AcubeSATParameters::epsCC2_CURR_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC3_CURR_IN_MPPT_RA,AcubeSATParameters::epsCC3_CURR_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC4_CURR_IN_MPPT_RA,AcubeSATParameters::epsCC4_CURR_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC5_CURR_IN_MPPT_RA,AcubeSATParameters::epsCC5_CURR_IN_MPPT_RA},
                  {AcubeSATParameters::EPS_CC1_VOLT_OU_MPPT_RA,AcubeSATParameters::epsCC1_VOLT_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC2_VOLT_OU_MPPT_RA,AcubeSATParameters::epsCC2_VOLT_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC3_VOLT_OU_MPPT_RA,AcubeSATParameters::epsCC3_VOLT_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC4_VOLT_OU_MPPT_RA,AcubeSATParameters::epsCC4_VOLT_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC5_VOLT_OU_MPPT_RA,AcubeSATParameters::epsCC5_VOLT_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC1_CURR_OU_MPPT_RA,AcubeSATParameters::epsCC1_CURR_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC2_CURR_OU_MPPT_RA,AcubeSATParameters::epsCC2_CURR_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC3_CURR_OU_MPPT_RA,AcubeSATParameters::epsCC3_CURR_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC4_CURR_OU_MPPT_RA,AcubeSATParameters::epsCC4_CURR_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CC5_CURR_OU_MPPT_RA,AcubeSATParameters::epsCC5_CURR_OU_MPPT_RA},
                  {AcubeSATParameters::EPS_CH_STARTUP_ENA_BF,AcubeSATParameters::epsCH_STARTUP_ENA_BF},
                  {AcubeSATParameters::EPS_CH_STARTUP_KEY,AcubeSATParameters::epsCH_STARTUP_KEY},
                  {AcubeSATParameters::EPS_CH_LATCHOFF_ENA_BF,AcubeSATParameters::epsCH_LATCHOFF_ENA_BF},
                  {AcubeSATParameters::EPS_CH_LATCHOFF_KEY,AcubeSATParameters::epsCH_LATCHOFF_KEY},
                  {AcubeSATParameters::EPS_TTC_WDG_TIMEOUT,AcubeSATParameters::epsTTC_WDG_TIMEOUT},
                  {AcubeSATParameters::EPS_TTC_WDG_TIMEOUT_KEY,AcubeSATParameters::epsTTC_WDG_TIMEOUT_KEY},
                  {AcubeSATParameters::EPS_CH_STARTUP_DELAY_CH1,AcubeSATParameters::epsCH_STARTUP_DELAY_CH1},
                  {AcubeSATParameters::EPS_CH_LATCHOFF_DELAY_CH1,AcubeSATParameters::epsCH_LATCHOFF_DELAY_CH1},
                  {AcubeSATParameters::EPS_SAFETY_VOLT_LOTHR,AcubeSATParameters::epsSAFETY_VOLT_LOTHR},
                  {AcubeSATParameters::EPS_SAFETY_VOLT_HITHR,AcubeSATParameters::epsSAFETY_VOLT_HITHR},
                  {AcubeSATParameters::EPS_LOTHR_BP1_HEATER,AcubeSATParameters::epsLOTHR_BP1_HEATER},
                  {AcubeSATParameters::EPS_LOTHR_BP2_HEATER,AcubeSATParameters::epsLOTHR_BP2_HEATER},
                  {AcubeSATParameters::EPS_LOTHR_BP3_HEATER,AcubeSATParameters::epsLOTHR_BP3_HEATER},
                  {AcubeSATParameters::EPS_HITHR_BP1_HEATER,AcubeSATParameters::epsHITHR_BP1_HEATER},
                  {AcubeSATParameters::EPS_HITHR_BP2_HEATER,AcubeSATParameters::epsHITHR_BP2_HEATER},
                  {AcubeSATParameters::EPS_HITHR_BP3_HEATER,AcubeSATParameters::epsHITHR_BP3_HEATER},
                  {AcubeSATParameters::EPS_LOTHR_BP1_UNBAL,AcubeSATParameters::epsLOTHR_BP1_UNBAL},
                  {AcubeSATParameters::EPS_LOTHR_BP2_UNBAL,AcubeSATParameters::epsLOTHR_BP2_UNBAL},
                  {AcubeSATParameters::EPS_LOTHR_BP3_UNBAL,AcubeSATParameters::epsLOTHR_BP3_UNBAL},
                  {AcubeSATParameters::EPS_HITHR_BP1_UNBAL,AcubeSATParameters::epsHITHR_BP1_UNBAL},
                  {AcubeSATParameters::EPS_HITHR_BP2_UNBAL,AcubeSATParameters::epsHITHR_BP2_UNBAL},
                  {AcubeSATParameters::EPS_HITHR_BP3_UNBAL,AcubeSATParameters::epsHITHR_BP3_UNBAL},
                  {AcubeSATParameters::EPS_MCU_TEMP_BIAS,AcubeSATParameters::epsMCU_TEMP_BIAS},
                  {AcubeSATParameters::EPS_MCU_TEMP_PREMUL,AcubeSATParameters::epsMCU_TEMP_PREMUL},
                  {AcubeSATParameters::EPS_MCU_TEMP_POSDIV,AcubeSATParameters::epsMCU_TEMP_POSDIV},
                  {AcubeSATParameters::EPS_BP1_TEMP1_BIAS,AcubeSATParameters::epsBP1_TEMP1_BIAS},
                  {AcubeSATParameters::EPS_BP1_TEMP2_BIAS,AcubeSATParameters::epsBP1_TEMP2_BIAS},
                  {AcubeSATParameters::EPS_BP1_TEMP3_BIAS,AcubeSATParameters::epsBP1_TEMP3_BIAS},
                  {AcubeSATParameters::EPS_BP2_TEMP1_BIAS,AcubeSATParameters::epsBP2_TEMP1_BIAS},
                  {AcubeSATParameters::EPS_BP2_TEMP2_BIAS,AcubeSATParameters::epsBP2_TEMP2_BIAS},
                  {AcubeSATParameters::EPS_BP2_TEMP3_BIAS,AcubeSATParameters::epsBP2_TEMP3_BIAS},
                  {AcubeSATParameters::EPS_BP3_TEMP1_BIAS,AcubeSATParameters::epsBP3_TEMP1_BIAS},
                  {AcubeSATParameters::EPS_BP3_TEMP2_BIAS,AcubeSATParameters::epsBP3_TEMP2_BIAS},
                  {AcubeSATParameters::EPS_BP3_TEMP3_BIAS,AcubeSATParameters::epsBP3_TEMP3_BIAS},
                  {AcubeSATParameters::EPS_BP1_TEMP1_PREMUL,AcubeSATParameters::epsBP1_TEMP1_PREMUL},
                  {AcubeSATParameters::EPS_BP1_TEMP2_PREMUL,AcubeSATParameters::epsBP1_TEMP2_PREMUL},
                  {AcubeSATParameters::EPS_BP1_TEMP3_PREMUL,AcubeSATParameters::epsBP1_TEMP3_PREMUL},
                  {AcubeSATParameters::EPS_BP2_TEMP1_PREMUL,AcubeSATParameters::epsBP2_TEMP1_PREMUL},
                  {AcubeSATParameters::EPS_BP2_TEMP2_PREMUL,AcubeSATParameters::epsBP2_TEMP2_PREMUL},
                  {AcubeSATParameters::EPS_BP2_TEMP3_PREMUL,AcubeSATParameters::epsBP2_TEMP3_PREMUL},
                  {AcubeSATParameters::EPS_BP3_TEMP1_PREMUL,AcubeSATParameters::epsBP3_TEMP1_PREMUL},
                  {AcubeSATParameters::EPS_BP3_TEMP2_PREMUL,AcubeSATParameters::epsBP3_TEMP2_PREMUL},
                  {AcubeSATParameters::EPS_BP3_TEMP3_PREMUL,AcubeSATParameters::epsBP3_TEMP3_PREMUL},
                  {AcubeSATParameters::EPS_BP1_TEMP1_POSDIV,AcubeSATParameters::epsBP1_TEMP1_POSDIV},
                  {AcubeSATParameters::EPS_BP1_TEMP2_POSDIV,AcubeSATParameters::epsBP1_TEMP2_POSDIV},
                  {AcubeSATParameters::EPS_BP1_TEMP3_POSDIV,AcubeSATParameters::epsBP1_TEMP3_POSDIV},
                  {AcubeSATParameters::EPS_BP2_TEMP1_POSDIV,AcubeSATParameters::epsBP2_TEMP1_POSDIV},
                  {AcubeSATParameters::EPS_BP2_TEMP2_POSDIV,AcubeSATParameters::epsBP2_TEMP2_POSDIV},
                  {AcubeSATParameters::EPS_BP2_TEMP3_POSDIV,AcubeSATParameters::epsBP2_TEMP3_POSDIV},
                  {AcubeSATParameters::EPS_BP3_TEMP1_POSDIV,AcubeSATParameters::epsBP3_TEMP1_POSDIV},
                  {AcubeSATParameters::EPS_BP3_TEMP2_POSDIV,AcubeSATParameters::epsBP3_TEMP2_POSDIV},
                  {AcubeSATParameters::EPS_BP3_TEMP3_POSDIV,AcubeSATParameters::epsBP3_TEMP3_POSDIV},
                  {AcubeSATParameters::EPS_BOARD_IDENTIFIER,AcubeSATParameters::epsBOARD_IDENTIFIER},
                  {AcubeSATParameters::EPS_BOARD_IDENTIFIER_KEY,AcubeSATParameters::epsBOARD_IDENTIFIER_KEY},
                  {AcubeSATParameters::EPS_RAVG_STRENGTH_P2,AcubeSATParameters::epsRAVG_STRENGTH_P2},
                  {AcubeSATParameters::EPS_AUTO_HEAT_ENA_BP1,AcubeSATParameters::epsAUTO_HEAT_ENA_BP1},
                  {AcubeSATParameters::EPS_AUTO_HEAT_ENA_BP2,AcubeSATParameters::epsAUTO_HEAT_ENA_BP2},
                  {AcubeSATParameters::EPS_AUTO_HEAT_ENA_BP3,AcubeSATParameters::epsAUTO_HEAT_ENA_BP3},
                  {AcubeSATParameters::EPS_AUTO_BAL_ENA_BP1,AcubeSATParameters::epsAUTO_BAL_ENA_BP1},
                  {AcubeSATParameters::EPS_AUTO_BAL_ENA_BP2,AcubeSATParameters::epsAUTO_BAL_ENA_BP2},
                  {AcubeSATParameters::EPS_AUTO_BAL_ENA_BP3,AcubeSATParameters::epsAUTO_BAL_ENA_BP3},
                  {AcubeSATParameters::EPS_VD1_ALWAYS_ENA,AcubeSATParameters::epsVD1_ALWAYS_ENA},
                  {AcubeSATParameters::EPS_VD1_ALWAYS_DISA,AcubeSATParameters::epsVD1_ALWAYS_DISA},
                  {AcubeSATParameters::EPS_CH_FORCE_ENA_USE_BF,AcubeSATParameters::epsCH_FORCE_ENA_USE_BF},
                  {AcubeSATParameters::EPS_CH_STARTUP_ENA_USE_BF,AcubeSATParameters::epsCH_STARTUP_ENA_USE_BF},
                  {AcubeSATParameters::EPS_CH_LATCHOFF_ENA_USE_BF,AcubeSATParameters::epsCH_LATCHOFF_ENA_USE_BF},
                  {AcubeSATParameters::EPS_VD1_ALLOC_CH_BF,AcubeSATParameters::epsVD1_ALLOC_CH_BF},
                  {AcubeSATParameters::EPS_SWCI_CH_CMD_ENA_BF,AcubeSATParameters::epsSWCI_CH_CMD_ENA_BF},
                  {AcubeSATParameters::EPS_SWCI_CH_CMD_DISA_BF,AcubeSATParameters::epsSWCI_CH_CMD_DISA_BF},
                  {AcubeSATParameters::EPS_TTC_I2C_SLAVE_ADDR,AcubeSATParameters::epsTTC_I2C_SLAVE_ADDR},
                  {AcubeSATParameters::EPS_CONF_NVM_SAVE_CNTR,AcubeSATParameters::epsCONF_NVM_SAVE_CNTR},
                  {AcubeSATParameters::EPS_CONF_NVM_SAVE_CHKS,AcubeSATParameters::epsCONF_NVM_SAVE_CHKS},
                  {AcubeSATParameters::EPS_RST_CAUSE,AcubeSATParameters::epsRST_CAUSE},
                  {AcubeSATParameters::EPS_RST_CNTR_PWRON,AcubeSATParameters::epsRST_CNTR_PWRON},
                  {AcubeSATParameters::EPS_RST_CNTR_WDG,AcubeSATParameters::epsRST_CNTR_WDG},
                  {AcubeSATParameters::EPS_RST_CNTR_CMD,AcubeSATParameters::epsRST_CNTR_CMD},
                  {AcubeSATParameters::EPS_RST_CNTR_MCU,AcubeSATParameters::epsRST_CNTR_MCU},
                  {AcubeSATParameters::EPS_RST_CNTR_EMLOPO,AcubeSATParameters::epsRST_CNTR_EMLOPO},
                  {AcubeSATParameters::EPS_RST_CODE_MCU_RAW,AcubeSATParameters::epsRST_CODE_MCU_RAW},
                  {AcubeSATParameters::EPS_EMLOPO_VOLT_LOTHR,AcubeSATParameters::epsEMLOPO_VOLT_LOTHR},
                  {AcubeSATParameters::EPS_EMLOPO_VOLT_HITHR,AcubeSATParameters::epsEMLOPO_VOLT_HITHR},
                  {AcubeSATParameters::EPS_EMLOPO_PERIOD,AcubeSATParameters::epsEMLOPO_PERIOD},
                  {AcubeSATParameters::EPS_SAFETY_VOLT_LOTHR_USED,AcubeSATParameters::epsSAFETY_VOLT_LOTHR_USED},
                  {AcubeSATParameters::EPS_SAFETY_VOLT_HITHR_USED,AcubeSATParameters::epsSAFETY_VOLT_HITHR_USED},
                  {AcubeSATParameters::EPS_SAFETY_LINGER,AcubeSATParameters::epsSAFETY_LINGER},
                  {AcubeSATParameters::EPS_TTC_WDG_TIMOUT_USED,AcubeSATParameters::epsTTC_WDG_TIMOUT_USED},
                  {AcubeSATParameters::EPS_TTC_PREVCMD_ELAPSED,AcubeSATParameters::epsTTC_PREVCMD_ELAPSED},
                  {AcubeSATParameters::EPS_STID,    AcubeSATParameters::epsSTID},
                  {AcubeSATParameters::EPS_IVID,    AcubeSATParameters::epsIVID},
                  {AcubeSATParameters::EPS_BID_USED,AcubeSATParameters::epsBID_USED},
                  {AcubeSATParameters::EPS_BOOT_RESUME_SHORT,AcubeSATParameters::epsBOOT_RESUME_SHORT},
                  {AcubeSATParameters::EPS_CONF_PARAM_CHANGED,AcubeSATParameters::epsCONF_PARAM_CHANGED},


                  //---------------------------------------------------------------------------------------------
                  {AcubeSATParameters::COMMSUHFBandPATemperature, AcubeSATParameters::commsUHFBandPATemperature},
                  {AcubeSATParameters::COMMSSBandPATemperature, AcubeSATParameters::commsSBandPATemperature},
                  {AcubeSATParameters::COMMSPCBTemperature, AcubeSATParameters::commsPCBTemperature},
                  {AcubeSATParameters::COMMSAntennaDeploymentStatus, AcubeSATParameters::commsAntennaDeploymentStatus},
                  {AcubeSATParameters::COMMSDataRateUHFTX, AcubeSATParameters::commsDataRateUHFTX},
                  {AcubeSATParameters::COMMSDataRateUHFRX, AcubeSATParameters::commsDataRateUHFRX},
                  {AcubeSATParameters::COMMSSymbolRateSBand, AcubeSATParameters::commsSymbolRateSBand},
                  {AcubeSATParameters::COMMSCWInterval, AcubeSATParameters::commsCWInterval},
                  {AcubeSATParameters::COMMSGMSKBeaconInterval, AcubeSATParameters::commsGMSKBeaconInterval},
                  {AcubeSATParameters::COMMSUHFBandTXPower, AcubeSATParameters::commsUHFBandTXPower},
                  {AcubeSATParameters::COMMSSBandTXPower, AcubeSATParameters::commsSBandTXPower},
                  {AcubeSATParameters::COMMSChannelNumberUHFBand, AcubeSATParameters::commsChannelNumberUHFBand},
                  {AcubeSATParameters::COMMSChannelNumberSBand, AcubeSATParameters::commsChannelNumberSBand},
                  {AcubeSATParameters::COMMSLNAGain, AcubeSATParameters::commsLNAGain},
                  {AcubeSATParameters::COMMSPAGainUHFBand, AcubeSATParameters::commsPAGainUHFBand},
                  {AcubeSATParameters::COMMSPAGainSBand, AcubeSATParameters::commsPAGainSBand},
                  {AcubeSATParameters::COMMSVGAGain, AcubeSATParameters::commsVGAGain},
                  {AcubeSATParameters::COMMSRSSI, AcubeSATParameters::commsRSSI},
                  {AcubeSATParameters::COMMSUHFBandTXOnOff, AcubeSATParameters::commsUHFBandTXOnOff},
                  {AcubeSATParameters::COMMSUHFBandRXOnOff, AcubeSATParameters::commsUHFBandRXOnOff},
                  {AcubeSATParameters::COMMSSBandTXOnOff, AcubeSATParameters::commsSBandTXOnOff},
                  {AcubeSATParameters::COMMSPacketsRejectedCOMMS, AcubeSATParameters::commsPacketsRejectedCOMMS},
                  {AcubeSATParameters::COMMSInvalidHMAC, AcubeSATParameters::commsInvalidHMAC},
                  {AcubeSATParameters::COMMSInvalidPacketStructure, AcubeSATParameters::commsInvalidPacketStructure},
                  {AcubeSATParameters::COMMSInvalidSpacecraftID, AcubeSATParameters::commsInvalidSpacecraftID},
                  {AcubeSATParameters::COMMSFrameSequenceCounter, AcubeSATParameters::commsFrameSequenceCounter},
                  {AcubeSATParameters::COMMSPCBTemperature1, AcubeSATParameters::commsPCBTemperature1},
                  {AcubeSATParameters::COMMSPCBTemperature2, AcubeSATParameters::commsPCBTemperature2},
                  {AcubeSATParameters::COMMSMCUTemperature, AcubeSATParameters::commsMCUTemperature},
                  {AcubeSATParameters::COMMSMCUInputVoltage, AcubeSATParameters::commsMCUInputVoltage},
                  {AcubeSATParameters::COMMSMCUBootCounter, AcubeSATParameters::commsMCUBootCounter},
                  {AcubeSATParameters::COMMSOnBoardTime, AcubeSATParameters::commsOnBoardTime},
                  {AcubeSATParameters::COMMSNANDCurrentlyUsedMemoryPartition, AcubeSATParameters::commsNANDCurrentlyUsedMemoryPartition},
                  {AcubeSATParameters::COMMSLastFailedEvent, AcubeSATParameters::commsLastFailedEvent},
                  {AcubeSATParameters::COMMSMCUSystick, AcubeSATParameters::commsMCUSystick},
                  {AcubeSATParameters::COMMSFlashInt, AcubeSATParameters::commsFlashInt},
                  {AcubeSATParameters::COMMSSRAMInt, AcubeSATParameters::commsSRAMInt}};
}

#endif
